const legacyEventFactory = ({
  event = "some event",
  category = "some category",
  tracking_id = "769f653b-40e3-428c-a493-ad3b43f1dded",
  userAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
  url = "https://www.ezcater.com/store/checkout/place_order/1d48ae6f-8897-4075-942b-3f7a4852db60",
  referrer_url = "https://www.ezcater.com/catering/panera-bread-charlotte-city-park-dr/2024-10-09?cartId=1d48ae6f-8897-4075-942b-3f7a4852db60",
  landing_url = "/store/checkout/place_order/1d48ae6f-8897-4075-942b-3f7a4852db60",
  platform_name = "Windows",
} = {}) => {
  return {
    application: "ezrails",
    event_props: {
      source: "javascript",
      type: "click",
      project: "ez_rails",
      event: event,
      category: category,
      ui_element_name: "set-tip-percent-10",
      utm_medium: "direct",
      utm_source: "direct",
      lead_channel: "direct",
      url: url,
      landing_url: landing_url,
      referrer_url: referrer_url,
      params_controller: "store/checkout/place_order",
      params_action: "show",
      page: "store/checkout/place_order show",
      order_id: 269804148,
      private_store: false,
      order_source: "marketplace",
      admin: false,
      ip_address: "1.2.3.4",
      misc_json: {
        cf_bot_score: "99",
        cf_verified_bot: "false",
      },
      browser_name: "Chrome",
      browser_version: "129",
      browser_full_version: "129.0.0.0",
      device_name: "Unknown",
      platform_name: platform_name,
      user_agent: userAgent,
      client: "web",
      unique_record_id: "dce2563a-5d24-48aa-ad6a-9c2a963c10a1",
    },
    user_props: {
      name: "Ziba HappyDog",
      email: "Ziba@happydog.com",
      opt_in: true,
      referral_code: "cc26310e99",
      user_created_at: "2021-07-13T11:10:15-0400",
      status: "CUSTOMER",
      enrolled_in_ez_rewards: true,
      state: "SC",
      admin: false,
      caterer: false,
      cohort_week: "2021-07-12 week",
      cohort_month: "2021-07-01 month",
    },
    datetime: "2024-10-04T13:03:54.364-0400",
    event_type: "Page: Clicked element on store/checkout/place_order show",
    display_name: "Page: Clicked element on store/checkout/place_order show",
    tracking_id: tracking_id,
    email: "Ziba@happydog.com",
    sub_category: null,
    event: event,
    category: category,
    original_user_agent: userAgent,
    user_agent: userAgent,
    referrer_url: referrer_url, // added for testing purposes
  };
};

export default legacyEventFactory;
